-- person
CREATE TABLE person (
    dni          NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    nameuser     VARCHAR2(100) NOT NULL,
    lastnameuser VARCHAR2(100) NOT NULL
);

-- company
CREATE TABLE company (
    companynro  NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    namecompany VARCHAR2(100) NOT NULL
);

-- place
CREATE TABLE place (
    placeid   NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    nameplace VARCHAR2(50) NOT NULL
);

-- phone
CREATE TABLE phone (
    phoneid     NUMBER(11)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    phonenumber VARCHAR2(20) NOT NULL,
    person_dni  NUMBER(5) NOT NULL,
    FOREIGN KEY ( person_dni )
        REFERENCES person ( dni )
            ON DELETE CASCADE
);

-- address
CREATE TABLE address (
    addressid   NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    addressname VARCHAR2(100) NOT NULL,
    person_dni  NUMBER(5) NOT NULL,
    FOREIGN KEY ( person_dni )
        REFERENCES person ( dni )
            ON DELETE CASCADE
);

-- ticket
CREATE TABLE ticket (
    ticketnro          NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
    PRIMARY KEY,
    dateticket         DATE NOT NULL,
    timeticket         TIMESTAMP NOT NULL,
    place_origin       NUMBER(5) NOT NULL,
    place_destination  NUMBER(5) NOT NULL,
    person_dni         NUMBER(5) NOT NULL,
    company_companynro NUMBER(5) NOT NULL,
    FOREIGN KEY ( place_origin )
        REFERENCES place ( placeid )
            ON DELETE CASCADE,
    FOREIGN KEY ( place_destination )
        REFERENCES place ( placeid )
            ON DELETE CASCADE,
    FOREIGN KEY ( person_dni )
        REFERENCES person ( dni )
            ON DELETE CASCADE,
    FOREIGN KEY ( company_companynro )
        REFERENCES company ( companynro )
            ON DELETE CASCADE
);