ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-- USER SQL
CREATE USER "DEMO" IDENTIFIED BY "demo"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "DEMO" ;
GRANT "RESOURCE" TO "DEMO" ;

-- SYSTEM PRIVILEGES
GRANT SELECT ANY TABLE TO "DEMO" ;
GRANT ALTER ANY TABLE TO "DEMO" ;
GRANT DELETE ANY TABLE TO "DEMO" ;
GRANT UPDATE ANY TABLE TO "DEMO" ;
GRANT INSERT ANY TABLE TO "DEMO" ;
GRANT UNLIMITED TABLESPACE TO "DEMO" ;
GRANT CREATE ANY TABLE TO "DEMO" ;